name: 'Dependency Review'

on:
  workflow_call:

jobs:
  dependency-review:
    name: Check dependencies
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v1
